# Generated by Django 6.0.2 on 2026-02-22 01:57

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='token_hash',
            field=models.CharField(default=apps.accounts.models.generate_invitation_token_hash, editable=False, max_length=64, unique=True),
        ),
    ]
