# Generated by Django 6.0.2 on 2026-03-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_invitation_token_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.URLField(max_length=250),
        ),
    ]
