# Generated by Django 6.0.2 on 2026-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profile_linkedin_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="invitee_name",
            field=models.CharField(default="", max_length=160),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invitation",
            name="used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="token_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
